global:
  resolve_timeout: 5m

route:
  group_by: ['server_is_down']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'stardata-telegram'

receivers:
  - name: 'stardata-telegram'
    telegram_configs:
      - bot_token: 7113240072:AAEfy5veB2vpwku2BOTm10YGGLAm1ILoh_c
        api_url: https://api.telegram.org
        chat_id: -4572060650
        parse_mode: ''