global:
  resolve_timeout: 5m

route:
  group_by: ['server_is_down']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'stardata-telegram'

receivers:
  - name: 'stardata-telegram'
    telegram_configs:
      - bot_token: PUT_YOUR_BOT_TOKEN_HERE
        api_url: https://api.telegram.org
        chat_id: PUT_YOUR_CHAT_ID_HERE
        parse_mode: ''