services:
  execution:
    image: ethereum/client-go:stable
    container_name: geth_execution
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ./geth_data:/root/.ethereum
      - ./jwtsecret:/root/jwtsecret
    command: >
      --holesky
      --http
      --http.addr "0.0.0.0"
      --http.port 8545
      --http.api "eth,net,web3"
      --datadir /root/.ethereum
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.vhosts="*"
      --authrpc.jwtsecret /root/jwtsecret

  consensus:
    image: sigp/lighthouse:latest
    container_name: lighthouse_consensus
    restart: unless-stopped
    ports:
      - "5052:5052"
      - "9000:9000/tcp"
      - "9000:9000/udp"
    volumes:
      - ./lighthouse_data:/root/.lighthouse
      - ./jwtsecret:/root/jwtsecret
    command: >
      lighthouse bn
      --network holesky
      --http
      --http-address 0.0.0.0
      --execution-endpoint http://geth_execution:8551
      --datadir /root/.lighthouse
      --checkpoint-sync-url=https://checkpoint-sync.holesky.ethpandaops.io
      --execution-jwt /root/jwtsecret
