version: "3.8"

services:
  #  ------------
  #  node
  #  ------------
  geth:
    image: ethereum/client-go:v1.14.8
    ports:
      - "6060:6060"
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    command: |
      --holesky
      --syncmode "snap"
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts="*"
      --http.api="db,eth,net,engine,rpc,web3"
      --authrpc.jwtsecret="/root/jwt/jwt.hex"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
      --log.file=/root/.ethereum/logs/geth.log
    networks: [eth-node]
    volumes:
      - ./data/geth:/root/.ethereum
      - ./jwt:/root/jwt
    restart: unless-stopped

  lighthouse:
    image: sigp/lighthouse:v5.3.0
    ports:
      - "5054:5054"
      - "5052:5052"
      - "9000:9000/tcp"
      - "9000:9000/udp"
    command: |
      lighthouse bn
      --network holesky
      --checkpoint-sync-url=https://checkpoint-sync.holesky.ethpandaops.io
      --execution-endpoint=http://geth:8551
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --metrics-allow-origin="*"
    networks: [eth-node]
    volumes:
      - ./data/lighthouse:/opt/app/beacon
      - ./jwt:/opt/jwt
    restart: unless-stopped

  #  ------------
  #  monitoring
  #  ------------
  prometheus:
    image: prom/prometheus:v2.43.0
    user: ":"
    ports:
      - "9090:9090"
    networks: [eth-node]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.7
    user: ":"
    ports:
      - "80:3000"
    networks: [eth-node]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:2.8.2
    user: ":"
    networks: [eth-node]
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./data/loki:/opt/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.8.2
    networks: [eth-node]
    volumes:
      - ./data/geth/logs:/geth-logs
      - ./data/lighthouse/beacon/logs:/lighthouse-logs
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    networks: [eth-node]
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    restart: unless-stopped

networks:
  eth-node:
