global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "geth"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["geth:6060"]
  - job_name: "lighthouse"
    static_configs:
      - targets: ["lighthouse:5054"]

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"