{
 "title": "Single Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Execution Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GETH",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"geth\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Peers connected with our execution client. Also number of peers we dialled and we are serving.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "peers" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory used by execution client.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rate(system_memory_allocs[1m])", "legendFormat": "alloc" },
    { "expr": "system_memory_used", "legendFormat": "used" },
    { "expr": "system_memory_held", "legendFormat": "held" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_sysload", "legendFormat": "system" },
    { "expr": "system_cpu_syswait", "legendFormat": "iowait" },
    { "expr": "system_cpu_procload", "legendFormat": "geth" }
   ]
  },
  {
   "title": "Latest Chain Header",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_header" }
   ]
  },
  { "title": "Beacon Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "LIGHTHOUSE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "description": "Lighthouse's reported current slot (unsafe not finalised)",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(slotclock_present_slot)" }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "The sync status for lighthouse's peers",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_peers_per_status", "legendFormat": "{{sync_status}}" }
   ]
  },
  {
   "title": "Eth1 Execution Client Connected",
   "type": "stat",
   "description": "Identifies if there is an upstream execution client connected",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sync_eth1_connected", "legendFormat": "{{range_type}}" }
   ]
  },
  {
   "title": "Eth2 Consensus Client Synced",
   "type": "stat",
   "description": "Identifies if the consensus client is synced",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sync_eth2_synced", "legendFormat": "{{range_type}}" }
   ]
  }
 ]
}